words:
  - achemso
  - amsthm
  - auctex
  - bhadauria
  - biber
  - cvis
  - dpth
  - dsrc
  - eledsec
  - expex
  - festag
  - feynmf
  - feynmp
  - gaux
  - glog
  - glsdefs
  - glstex
  - gomod
  - gtex
  - gummi
  - htlatex
  - jisuanji
  - kapil
  - khabaz
  - kile
  - knitr
  - latexmk
  - liblaf
  - ltjruby
  - luatexja
  - nofootinbib
  - pdfpc
  - pdfpcnotes
  - pytxcode
  - sarita
  - scmd
  - scrwfile
  - sehla
  - shuqiang
  - sout
  - sympy
  - tcolorbox
  - texpadtmp
  - thmtools
  - vhistory
  - xcolor
  - xindy
  - xmpi
  - xnic
  - xwatermark
  - xypic
  - yingyong
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - latex
  - makefile
  - npm
allowCompoundWords: true
