words:
  - achemso
  - amsthm
  - auctex
  - biber
  - daxue
  - dpth
  - dsrc
  - eledsec
  - expex
  - feynmf
  - feynmp
  - gaux
  - ghafoor
  - glog
  - glsdefs
  - glstex
  - gnutella
  - gomod
  - gtex
  - gummi
  - htlatex
  - intelli
  - intelliway
  - jishu
  - jisuanji
  - kile
  - knitr
  - latexmk
  - liblaf
  - ltjruby
  - luatexja
  - naturalium
  - nofootinbib
  - pdfpc
  - pdfpcnotes
  - procedia
  - pytxcode
  - scientiarum
  - scmd
  - scrwfile
  - sout
  - sunyatseni
  - sympy
  - tcolorbox
  - texpadtmp
  - thmtools
  - tielu
  - tongxin
  - universitatis
  - vhistory
  - xcolor
  - xindy
  - xinhao
  - xmpi
  - xnic
  - xuebao
  - xuyu
  - xwatermark
  - xypic
  - yingyong
  - zhongshan
  - zrar
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - latex
  - makefile
  - npm
allowCompoundWords: true
