words:
  - achemso
  - amsthm
  - auctex
  - biber
  - dpth
  - dsrc
  - eledsec
  - expex
  - feynmf
  - feynmp
  - gaux
  - glog
  - glsdefs
  - glstex
  - gomod
  - "gonz\xE1lez"
  - gtex
  - gummi
  - htlatex
  - kile
  - knitr
  - ladar
  - latexmk
  - liblaf
  - ltjruby
  - luatexja
  - mertz
  - milanes
  - nashashibi
  - nofootinbib
  - odometry
  - pdfpc
  - pdfpcnotes
  - petrovskaya
  - pytxcode
  - "p\xE9rez"
  - scmd
  - scrwfile
  - serment
  - sout
  - sympy
  - tcolorbox
  - texpadtmp
  - thmtools
  - thrun
  - vhistory
  - xcolor
  - xindy
  - xmpi
  - xnic
  - xwatermark
  - xypic
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - latex
  - makefile
  - npm
allowCompoundWords: true
